### PR TITLE
Fix: Exception thrown when delta of scroll is 0

### LINKED ISSUE #21: Exception when scrolling through skill queue
Sometimes when I scroll through the skill queue I get the following exception:

EVEMon Version: 3.0.2.4644
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.14393.0
Executable Path: "F:\Projects\evemon\src\EVEMon\bin\Debug\EVEMon.exe" 

System.DivideByZeroException: Attempted to divide by zero.
   at EVEMon.CharacterMonitoring.CharacterSkillsList.lbSkills_MouseWheel(Object sender, MouseEventArgs e) in EVEMon\CharacterMonitoring\CharacterSkillsList.cs:line 624
   at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at EVEMon.Common.Controls.NoFlickerListBox.WndProc(Message& m) in EVEMon.Common\Controls\NoFlickerListBox.cs:line 56
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (193KiB - 8d9de77fb1705dd1e739ba10c583eb03)
  eve-certificates-en-US.xml.gzip (44KiB - e30974b3980b6bd80f21b71ffa1d0ebd)
  eve-geography-en-US.xml.gzip (531KiB - c60dd6b987340ff7d848f7eedc5a39c4)
  eve-items-en-US.xml.gzip (1761KiB - b534807e3fbd97ff8955a024fd8bc93b)
  eve-masteries-en-US.xml.gzip (20KiB - 7b07e6d5609b7277c3cbf4e486430240)
  eve-properties-en-US.xml.gzip (53KiB - 6c5771edd993e540d77679daf91e2c35)
  eve-reprocessing-en-US.xml.gzip (97KiB - 0274d4572164cf2ecdebc36b887886fd)
  eve-skills-en-US.xml.gzip (23KiB - 72e19887522d7cf27e077406618e3872)

I will shoot in a PR for a fix for this :).

### PR DESCRIPTION
**Pull request by Rutix**
Added a check to ignore scrollwheel events when the delta is 0.

Closes #21

### CODE REVIEW

**Comment by Rutix** [comment]
>.< This PR can be closed. Just saw that @elliena-bulmer added a fix for this in f338a9c . The commits are hidden in a different pull request though (PR 14) so thats why I didn't see this was fixed.

**Comment by Rutix** [comment]
Actually the fixes from f338a9c are part of another PR (PR #14 ) which makes it kinda messy tracking wise. Might be handier to merge this one and then remove the fixes from PR #14 but its your call @JimiC  :)

**Comment by elliena-bulmer** [comment]
@JimiC , I'll try to do proper pull requests for this fix. Sorry, learning :(

**Comment by JimiC** [comment]
@elliena-bulmer I'm no longer the maintainer of EVEMon, @blitzbandis has taken over. He should had updated the README doc to reflect this change. Sorry for any inconvenience.

**Comment by Ashilta** [comment]
I shall close this, as we've agreed that Elliena already has a PR for this fix. Thanks for contributing anyway.

**Comment by Rutix** [comment]
@Ashilta can we please merge PR #24 then? It's a damn annoying bug :/

**Comment by Ashilta** [comment]
@Rutix Soon! I'm working on getting familiar with the code and updating the data files to use the latest SDE. After I'm sure that's working then I'll merge the PR's that relate to bug fixes and release.

**Pull request closed without merging**
