### PR TITLE
Fix for Issue #12 (Fails to parse Wallet Journal)

### PR DESCRIPTION
**Pull request by elliena-bulmer**
Added a check to see if the the wallet transaction was done in a citadel or station. Also added a temporary constructor for the station in the meantime that a proper citadel system is done. In the wallet transaction, it'll just list as 'Citadel' but it won't skip lines when the purchase had been done in a citadel. The Wallet journal serialization is also now using a Long instead of an Int for the ID.

Ideally, we should make an interface for Citadel/Stations and use this in the WalletJournal system. Also, the citadel should probably be resolved using the CREST API, although, i haven't found the route in order to query, As soon as I find it, I'll add the proper system to resolve the information.

Note: don't mind the 4 commit, Bad account was set in my git.

### CODE REVIEW

**Comment by Rutix** [comment]
@elliena-bulmer This pull request is a little bit confusing. It has commits for multiple issues (issue #18 for example) which made that I missed it. This is probably because you don't use separate branches for your PR's which causes the PR to be updated when you push to master. Might be worth it to fix it :) and just a separate branch for issue #12 and issue #18 . Also another tip is to set up your git to do rebase when you pull so you dont get commit messages as "Pull from origin"

**Comment by elliena-bulmer** [comment]
Thanks @Rutix for the info on multiple branch for PRs, I was not aware of the proper way to do it, I'll see if I can update my PR and do it properly this time with proper branching.  gotta love learning Github :D

**Comment by Rutix** [comment]
@elliena-bulmer : No problem! I had to learn it the hard way in the past too :). A general rule of the thumb is to create branches for each feature/bug you are working on. This allows you to be able to keep "master" up to date with the main repository and still work on your changes :). I don't know if github allows repointing a PR to a different branch. If it doesn't I would just create a new branch, apply the changes on there and make a new one. And then close this one. Good luck!

**Comment by elliena-bulmer** [comment]
Closing this PR since I've sent new properly done PRs (hopefully). Thanks @Rutix for the wise information! I have to agree, it's much easier once you know about using branches for PR! :+1:

**Pull request closed without merging**
